CREATE DATABASE BamazonDB;

USE BamazonDB;

CREATE TABLE Product_Table(
 ItemID INT NOT NULL AUTO_INCREMENT,
 ProductName VARCHAR(100) NOT NULL,
 DepartmentName VARCHAR(100) NOT NULL,
 StockQuantitiy INT(10) NOT NULL,
 PRIMARY KEY (ItemID)
);
